<?php
include("../../simple_html_dom.php");
$dates_file="nizamabad_daily_update_dates.txt";
$json_file="nizamabad_json.json";
$state="Telangana";
$district="Nizamabad";
error_reporting(0);
getData("https://market.todaypricerates.com/Nizamabad-vegetables-price-in-Telangana",$dates_file,$json_file,$state,$district);
?>