<?php
include("../../simple_html_dom.php");
$dates_file="warangal_daily_update_dates.txt";
$json_file="warangal_json.json";
$state="Telangana";
$district="Warangal";
error_reporting(0);
getData("https://market.todaypricerates.com/Warangal-vegetables-price-in-Telangana",$dates_file,$json_file,$state,$district);
?>